mattermost:
  image: mattermost/platform:2.2
  ports:
    - "8080:80"

initializer:
  image: jwiii/mmm4s-init:0.1
  dns:
    - "172.17.0.1"
  dns_search:
    - "service.consul"
  links:
    - "mattermost"
  entrypoint: /mm4s/bin/wait-for-it.sh -t 60 mattermost:80 -- /mm4s/bin/mmaccounts.sh
