mattermost:
  image: jwiii/mattermost:2.2
  ports:
    - "8080:80"

initializer:
  image: jwiii/mm4s-init:0.1
  links:
    - "mattermost"
  entrypoint: /mm4s/bin/wait-for-it.sh -t 60 mattermost:80 -- /mm4s/bin/mmaccounts.sh
